language: csharp
sudo: required
solution: BaseFramework.sln
dist: bionic
services:
  - postgresql

matrix:
  include:
    - dotnet: 2.2.204
      mono: none
      os: linux

before_install:
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get install -y php7.3 php7.3-pgsql curl
  - sudo curl -s https://getcomposer.org/installer | php
  - sudo mv composer.phar /usr/local/bin/composer

before_script:
  - psql -c 'create database base_framework_test;' -U postgres

  - cp .travis/phinx.yml.testing migrations/phinx.yml
  - (cd migrations && composer install)
  - (cd migrations && php vendor/bin/phinx migrate -e testing)

  - mkdir -p Tests/bin/Debug/netcoreapp2.2/config
  - cp .travis/config.json.testing Tests/bin/Debug/netcoreapp2.2/config/config.json

script:
  - dotnet --version
  - dotnet test
