language: csharp
sudo: required
dist: trusty

matrix:
  include:
    - dotnet: latest
      mono: none
      os: linux
    - dotnet: latest
      mono: none
      os: osx
    - mono: latest
      os: linux
    - mono: latest
      os: osx

script:
  - ls
