language: csharp
sudo: required
solution: BaseFramework.sln
dist: bionic

matrix:
  include:
    - dotnet: 2.1.502
      mono: none
      os: linux
    - dotnet: 2.1.502
      mono: none
      os: osx

script:
  - ls
